remote server deployment

diff --git a/Jenkinsfile_local_deployment b/Jenkinsfile_local_deployment
--- a/Jenkinsfile_local_deployment
+++ b/Jenkinsfile_local_deployment
@@ -106,20 +106,34 @@ pipeline {
         }
 
     stage('Deploy') {
-    steps {
-        sshagent(credentials: ['server-ssh-key']) {
-            sh """
-            ssh -o StrictHostKeyChecking=no ubuntu@ec2-52-59-219-191.eu-central-1.compute.amazonaws.com '
-                docker pull egamor/jenkins-flask-app:latest &&
-                docker stop flask-app || true &&
-                docker rm flask-app || true &&
-                docker run -d --name flask-app -p 5000:5000 egamor/jenkins-flask-app:latest
-            '
-            """
-        }
-    }
-}
+       
+            steps {
+                sh '''
+                    echo "Deploying Flask app locally..."
 
+                    CONTAINER_NAME="flask-app"
+
+                    # Stop existing container if running
+                    if [ $(docker ps -q -f name=$CONTAINER_NAME) ]; then
+                        echo "Stopping existing container..."
+                        docker stop $CONTAINER_NAME && docker rm $CONTAINER_NAME
+                    fi
+
+                    # Run new container
+                    docker run -d --name $CONTAINER_NAME -p 5000:5000 ${IMAGE_NAME}:latest
+
+                    # Optional: check if container started
+                    if [ $(docker ps -q -f name=$CONTAINER_NAME) ]; then
+                        echo "Deployment successful!"
+                    else
+                        echo "Deployment failed!"
+                        exit 1
+                    fi
+                '''
+            }
+        }
+
+    }
 
 }
 
